- hosts: app
  gather_facts: no
  vars:
    image: auth
    docker_user: '{{ lookup("env", "DOCKER_USER") }}'
    docker_password: '{{ lookup("env", "DOCKER_PASSWORD") }}'
    registry: docker.pkg.github.com
    repository: '{{ registry }}/{{ docker_user }}/auth_microservice/{{ image }}'
  tasks:
    - name: build docker image
      delegate_to: 127.0.0.1
      docker_image:
        build:
          path: ../
          pull: no
        name: '{{ image }}'
        source: build
        force_source: yes
    - name: login to docker registry
      delegate_to: 127.0.0.1
      docker_login:
        registry: '{{ registry }}'
        username: '{{ docker_user }}'
        password: '{{ docker_password }}'
        reauthorize: yes
        debug: yes
    - name: push image
      delegate_to: 127.0.0.1
      docker_image:
        name: '{{ image }}'
        repository: '{{ repository }}'
        push: yes
        source: local
        force_tag: yes
    - name: login to docker registry on remote
      become: yes
      docker_login:
        registry: '{{ registry }}'
        username: '{{ docker_user }}'
        password: '{{ docker_password }}'
        reauthorize: yes
    - name: pull image on remote
      become: yes
      docker_image:
        name: '{{ repository }}'
        source: pull
        force_source: yes
    - name: run database migrations
      become: yes
      run_once: yes
      docker_container:
        name: auth-migrations
        image: '{{ repository }}'
        network_mode: host
        detach: no
        cleanup: yes
        command: bin/rake db:migrate
        env_file: '/home/{{ ansible_user }}/.env'
    - name: start app container
      become: yes
      docker_container:
        name: auth
        image: '{{ repository }}'
        ports:
          - "3010:3010"
        network_mode: host
        detach: no
        volumes:
          - /var/log:/var/log/app.log:ro
        command: bin/puma -p 3010
        restart_policy: on-failure
        restart_retries: 10
        env_file: '/home/{{ ansible_user }}/.env'
        state: started
