default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ads_dev

test:
  <<: *default
  database: ads_test

production:
  <<: *default
  database: ads_prod
  username: ads
  password: <%= ENV['ADS_DATABASE_PASSWORD'] %>
