db:
  database: auth_database_production
  url: <%= ENV.fetch('AUTH_DATABASE_URL') %>

rabbitmq:
  host: <%= ENV.fetch('RABBITMQ_HOST')%>
  username: <%= ENV.fetch('RABBITMQ_USER')%>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD')%>
